### ISSUE TITLE
테라폼(Terraform)으로 관리하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#1]
여력이 되면 하면 좋음

#### Activity
- Hyeon Kim added [this card](https://trello.com/c/KNXNLrl0) to Backlog - Sep 15 at 9:30 PM
- Hyeon Kim archived this card - Dec 22 at 10:14 PM
- Hyeon Kim sent this card to the board - Dec 23 at 3:57 PM

##### Reference
- https://www.terraform.io/

**Comment by lens0021** [comment]
EC2 인스턴스들에서 `docker stack deploy` 같은 프로비저닝 과정은 AMI에 포함되도록 패커에서 하는 것과 테라폼에 넣는 것 중 어느 게 나을까요?

**Comment by simnalamburt** [comment]
AWS EC2 유저데이터에 넣어야해요
