### ISSUE TITLE
CloudWatch Alarm 디스코드 채널로 쏘기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#24]

**Comment by lens0021** [comment]
SNS subcription에서 바로 웹훅을 연결할 수는 없는 것 같고, Amazon Lambda를 한 번 거쳐서 가야 할 것 같아요, 근데 혹시 그것도 또 바로는 안 되면 SQS를 중간에 낄 수도 있고요

**Comment by simnalamburt** [comment]
https://docs.aws.amazon.com/sns/latest/dg/sns-lambda-as-subscriber.html 얘 보면 SQS 사이에 안넣어도 SNS에서 람다를 바로 호출할 수 있는것같네요

**Comment by simnalamburt** [comment]
"AWS SNS - 람다 - 디스코드 웹훅" 이 방식으로 구현함

##### Reference
- https://github.com/femiwiki/sns-discord

**Comment by lens0021** [comment]
Route53가 있는 us-east-1 리전 것들은 쏘고 있었는데 저희가 주로 사용하는 ap-northeast-1 것들은 안 쏴지고 있었어서 다시 엽니다

**Comment by lens0021** [comment]
수동으로 똑같은 거(함수랑 트리거랑 `WEBHOOK_TOKEN` 환경 변수) 하나 더 도쿄 리전에 추가했습니다 :smile: 
테라폼은 추가할 게 없어서 그대로입니다 :sweat_smile:
