### ISSUE TITLE
멤버 정보 자동으로 암호화하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#25]
TBD

~~멤버들 관리까지 다 테라폼으로 하니까 관리가 오히려 어려운 것 같습니다. 예를 들어 초대를 하고 `terraform import`를 한번씩 더 해야 한다든가... 아예 뺐으면 합니다.~~

**Comment by lens0021** [comment]
> **simnalamburt**: 초대하고 테라폼 임포트 하지말고
> 코드 먼저 고치면
> 테라폼이 임시비번을 해당 사람의 keybase pgp 키 써서 암호화해주고
> 그거 읽어다가 로그인도하고
> 그럴수있지않나여
> **Lens0021**: IAM 같은 경우에는 생성하면서 랜덤 제네레이트 비밀번호 받기도 해야하는데 그건 혹시
> 어떻게 될까요?
> 할수 있으면 그냥 말구
> **simnalamburt**: 랜덤제네레이트 비밀번호가
> 그 사람의 keybase PGP 키로 암호화가 되어서
> 테라폼 state에 저장되구요
> 걍 (링크 올려도 되나 허락 맡는 중 --편집자주) 이거 보세요

> **lens0021**: 저런게 돼??
> **simnalamburt**: `terraform console <<< local.iam_secrets.simnalamburt` 이러면 읽을수도있고
> **lens0021**: 그럼 저걸 쓰는걸로 이슈를 고치겠읍니다
> 
> -- 페미위키 디스코드 #개발팀  채널

위 대화에 따라 이슈 변경합니다

**Comment by simnalamburt** [comment]
Closed by https://github.com/femiwiki/infra/commit/b58f9b624d5f752fad1880a4a0594bd6aab7b50b
