### ISSUE TITLE
Creating a new GitHub repository always fails at the first time

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#26]
```
Error: PUT https://api.github.com/repos/femiwiki/AchievementBadges/branches/master/protection: 404 Branch not found []

  on github.tf line 124, in resource "github_branch_protection" "extension_protections":
 124: resource "github_branch_protection" "extension_protections" {
```

https://app.terraform.io/app/femiwiki/workspaces/github/runs/run-6ANhKStXkYSonZ59

[`auto_init`](https://www.terraform.io/docs/providers/github/r/repository.html#auto_init)을 사용하면 어떻게 되는지 테스트 후 적용

**Comment by simnalamburt** [comment]
애초에 리포지터리 생성을 테라폼으로 하지 말고 그냥 브랜치 프로텍션이나 레이블 지정같은것만 테라폼으로 하는건 어떨까요?

**Comment by lens0021** [comment]
```tf
  has_projects  = false
  has_wiki      = false
```
위 내용 때문에 필요하지 않을까 합니다. 테라폼 작성하면서 몇 리포들의 설정을 고치기도 했어요.

**Comment by simnalamburt** [comment]
Oh shit..

2020년 1월 6일 (월) 00:38, Lens0021 <notifications@github.com>님이 작성:

**Comment by lens0021** [comment]
`auto_init = true`로 한 경우 다음과 같이 잘 생성되었습니다: https://github.com/femiwiki/remote-gadgets/commit/94e3c4b

**Comment by simnalamburt** [comment]
그럼 닫을 수 있는건가용

**Comment by lens0021** [comment]
닫조머머
