### ISSUE TITLE
terraform-cloud 워크스페이스 없애기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/infra#67]
@lens0021 terraform-cloud 워크스페이스 없애는거 어떻게 생각하시나요?

테라폼 워크스페이스랑 깃헙을 OAuth 앱 대신 GitHub Apps로 연결했더니, 죽어도 테라폼으로는 테라폼 클라우드를 관리할 수 없는 상태에 빠졌네요. https://github.com/terraform-providers/terraform-provider-tfe/issues/147 가 해결되지 않는이상 저희의 테라폼 워크스페이스들을 테라폼으로 관리할 수 없을것같습니다. 선택지가 두개 있는데

1. 원상복귀하기 (OAuth 앱을 다시 만들고, oauth 앱으로 깃헙과 테라폼 연결)
2. terraform-cloud 안쓰기

개인적으로 https://github.com/terraform-providers/terraform-provider-tfe/issues/147 해결되기 전까지는 걍 2로 가는게 어떨까 싶습니다. 저희가 terraform-cloud를 써서 유의미하게 관리하는 정보가 사실 테라폼 버전이랑 auto_apply 여부가 전부인데, 이걸 위해 깃헙에 OAuth app을 만들고 깃헙과 테라폼 클라우드 양쪽에 관련 정보를 넣어주는건 뭔가 주객이 전도된듯한 느낌이 들어서요.

힘들게 만드셨는데 없애자고해서 죄송합니다(..) 어떻게 생각하십니까

**Comment by lens0021** [comment]
없애도 상관 없을 것 같습니다. 말씀하신 이슈가 해결되었을 때 바로 다시 생성할 수 있으면 좋겠습니다 :smile:
