### ISSUE TITLE
UI/VCS-driven Run 활성화

### ISSUE THREAD

**Issue by lens0021** [femiwiki/infra#7]
- [x] Terraform Cloud 팀 멤버 전원 2FA 활성화
- Terraform Working Directory 활성화
  - [x] AWS
  - [x] github
- Execution Mode 설정
  - [x] AWS: Local &rarr; Remote + Manual apply 적용
  - [x] github: Remote + Auto apply 적용
- authen
- AWS
  - [x] Terraform용 IAM 유저 생성(credentials 저장해야 하니 콘솔가서 손으로 생성)
    - [x] `terraform import`
  - [x] 위 토큰 Terraform Cloud에 sensitive로 저장
  - [x] Policy 찾든 만들든 해서 붙이기
  - [x] 테라폼 코드 작성 &rarr; https://github.com/femiwiki/infra/commit/f4566e7
- Github
  - [x] 토큰 설정 @femiwiki-bot에게 `admin:org, read:packages, read:user, repo, workflow, write:discussion, write:packages`를 허용하는 토큰을 생성해 테라폼 클라우드에 환경 변수로 sensitive를 체크해 추가함
- Notifications에 디스코드 웹훅 추가:  Needs Attention, Applying, Completed, Errored 만 체크(Created와 Planning 제외됨)
  - [x] aws
  - [x] github

**Comment by lens0021** [comment]
@HanbitGaram 님 혹시 테라폼 클라우드 2FA 활성화 부탁드려도 될까요? 감사합니다 :smile: 

\> **[Two Factor Authentication 링크](https://app.terraform.io/app/settings/two-factor)**

**Comment by lens0021** [comment]
Claimed! @HanbitGaram

**Comment by lens0021** [comment]
우선 @HanbitGaram 님 멤버에서 제외하고 진행할게요 시간 되시면 얘기 주시면 도로 추가할게요 :sob:

**Comment by simnalamburt** [comment]
페미위키에서 내쫓는다는게 아니라 app.terraform.io 에서만 뺀다는 뜻이에여

**Comment by simnalamburt** [comment]
> 테라폼 UI/VCS-driven Run를
> AWS는 Manual apply
> github은 Auto apply로 적용했습니다 참고해주세요

이거 AWS만 수동으로 놓으신건 실수할까봐 그러신건가요?

**Comment by lens0021** [comment]
네네 혹시 그럴까봐 그랬는데 문제 없으면 Auto로 해도 저는 좋습니다 :)

**Comment by simnalamburt** [comment]
UI/VCS-driven run이 PR 날리면 plan 보여주는 기능이 있다네요. 이거때문에 켰으면 좋겠는데 Plan 어디에 뜨는지 혹시 보셨나요?

**Comment by lens0021** [comment]
![image](https://user-images.githubusercontent.com/28209361/68568564-414b8180-049f-11ea-86d6-72fd4a4a08ad.png)

https://github.com/femiwiki/infra/pull/14 여기에서 체크 한번 살펴보시면 나오는거 확인하실 수 있습니다 링크 클릭하면 나옵니다~

**Comment by simnalamburt** [comment]
Manual로 해도 PR에 plan은 다 뜨네요? 걍 Manual로 둘게요
